/**
 * Storefront — demo veri.
 *
 * Faz 5'te backend henüz tamamen hazır olmadığından temaların çalıştığını
 * göstermek için InMemoryStorefrontData sağlar. Production'da backend
 * hazır olduğunda bu dosya kullanılmaz.
 */

import type { InMemoryStorefrontData } from '@eticart/storefront-sdk';
import type { StorefrontBanner, StorefrontCategory, StorefrontBrand, StorefrontTestimonial, StorefrontProductSummary } from '@eticart/storefront-sdk';

const products: StorefrontProductSummary[] = [
  {
    id: 'p-001',
    slug: 'pamuklu-elbise',
    title: 'Pamuklu Yazlık Elbise',
    shortDescription: 'Hafif, nefes alabilir kumaş',
    priceKurus: 49900,
    compareAtKurus: 59900,
    currency: 'TRY',
    mainImageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800',
    inStock: true,
    isNew: true,
    isFeatured: true,
    isBestSeller: false,
    rating: 4.6,
    reviewCount: 24,
    brandName: 'ModaLine',
  },
  {
    id: 'p-002',
    slug: 'erkek-tisort',
    title: 'Erkek Pamuklu Tişört',
    shortDescription: 'Rahat kesim, çok renkli',
    priceKurus: 19900,
    compareAtKurus: null,
    currency: 'TRY',
    mainImageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
    inStock: true,
    isNew: false,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.4,
    reviewCount: 132,
    brandName: 'BasicWear',
  },
  {
    id: 'p-003',
    slug: 'deri-canta',
    title: 'El Yapımı Deri Çanta',
    shortDescription: 'Doğal deri, gerçek el işçiliği',
    priceKurus: 89900,
    compareAtKurus: 109900,
    currency: 'TRY',
    mainImageUrl: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=800',
    inStock: true,
    isNew: false,
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 67,
    brandName: 'Artizan',
  },
  {
    id: 'p-004',
    slug: 'spor-ayakkabi',
    title: 'Hafif Spor Ayakkabı',
    shortDescription: 'Nefes alabilir file tabanlık',
    priceKurus: 79900,
    compareAtKurus: null,
    currency: 'TRY',
    mainImageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
    inStock: true,
    isNew: true,
    isFeatured: true,
    isBestSeller: false,
    rating: 4.5,
    reviewCount: 89,
    brandName: 'SportFlex',
  },
  {
    id: 'p-005',
    slug: 'yün-kazak',
    title: 'Yün Karışım Kazak',
    shortDescription: 'Sıcak tutan, yumuşak dokulu',
    priceKurus: 39900,
    compareAtKurus: 49900,
    currency: 'TRY',
    mainImageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800',
    inStock: true,
    isNew: false,
    isFeatured: false,
    isBestSeller: true,
    rating: 4.3,
    reviewCount: 56,
    brandName: 'BasicWear',
  },
  {
    id: 'p-006',
    slug: 'klasik-jean',
    title: 'Klasik Kesim Jean',
    shortDescription: 'Yıkamalı, klasik mavi',
    priceKurus: 59900,
    compareAtKurus: null,
    currency: 'TRY',
    mainImageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800',
    inStock: true,
    isNew: false,
    isFeatured: false,
    isBestSeller: true,
    rating: 4.2,
    reviewCount: 178,
    brandName: 'DenimCo',
  },
  {
    id: 'p-007',
    slug: 'gunes-gozlugu',
    title: 'UV Korumalı Güneş Gözlüğü',
    shortDescription: 'Polarize cam',
    priceKurus: 29900,
    compareAtKurus: null,
    currency: 'TRY',
    mainImageUrl: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800',
    inStock: false,
    isNew: false,
    isFeatured: false,
    isBestSeller: false,
    rating: null,
    reviewCount: 0,
    brandName: 'SunView',
  },
  {
    id: 'p-008',
    slug: 'kolye',
    title: 'Gümüş Kolye',
    shortDescription: '925 ayar gümüş',
    priceKurus: 14900,
    compareAtKurus: 19900,
    currency: 'TRY',
    mainImageUrl: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800',
    inStock: true,
    isNew: true,
    isFeatured: false,
    isBestSeller: false,
    rating: 4.9,
    reviewCount: 14,
    brandName: 'SilverArt',
  },
];

const categories: StorefrontCategory[] = [
  {
    id: 'c-001',
    slug: 'kadin',
    name: 'Kadın',
    description: 'Kadın giyim',
    imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400',
    productCount: 3,
    children: [
      { id: 'c-001-1', slug: 'elbiseler', name: 'Elbiseler', description: null, imageUrl: null, productCount: 1, children: [] },
      { id: 'c-001-2', slug: 'tisortler', name: 'Tişörtler', description: null, imageUrl: null, productCount: 1, children: [] },
    ],
  },
  {
    id: 'c-002',
    slug: 'erkek',
    name: 'Erkek',
    description: 'Erkek giyim',
    imageUrl: 'https://images.unsplash.com/photo-1490578474895-699cd4e2cf59?w=400',
    productCount: 3,
    children: [],
  },
  {
    id: 'c-003',
    slug: 'aksesuar',
    name: 'Aksesuar',
    description: 'Çanta, gözlük, takı',
    imageUrl: null,
    productCount: 2,
    children: [],
  },
];

const brands: StorefrontBrand[] = [
  { id: 'b-001', slug: 'modaline', name: 'ModaLine', logoUrl: null, productCount: 1 },
  { id: 'b-002', slug: 'basicwear', name: 'BasicWear', logoUrl: null, productCount: 2 },
  { id: 'b-003', slug: 'artizan', name: 'Artizan', logoUrl: null, productCount: 1 },
  { id: 'b-004', slug: 'sportflex', name: 'SportFlex', logoUrl: null, productCount: 1 },
  { id: 'b-005', slug: 'denimco', name: 'DenimCo', logoUrl: null, productCount: 1 },
  { id: 'b-006', slug: 'silverart', name: 'SilverArt', logoUrl: null, productCount: 1 },
];

const banners: StorefrontBanner[] = [
  {
    id: 'bn-001',
    title: 'Yaz Koleksiyonu',
    subtitle: 'Tüm elbiselerde %30 indirim',
    imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1600',
    imageMobileUrl: null,
    ctaLabel: 'Koleksiyonu Keşfet',
    ctaHref: '/koleksiyon/yaz',
    order: 1,
  },
  {
    id: 'bn-002',
    title: 'Yeni Sezon',
    subtitle: '2026 İlkbahar / Yaz',
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=1600',
    imageMobileUrl: null,
    ctaLabel: 'Yeni Gelenler',
    ctaHref: '/koleksiyon/yeni',
    order: 2,
  },
];

const testimonials: StorefrontTestimonial[] = [
  {
    id: 't-001',
    customerName: 'Ayşe K.',
    customerTitle: 'İstanbul',
    rating: 5,
    comment: 'Ürünler beklediğimden çok daha kaliteli geldi. Kargo da hızlıydı, kesinlikle tavsiye ederim.',
    avatarUrl: null,
    approvedAt: '2026-01-15T10:00:00.000Z',
  },
  {
    id: 't-002',
    customerName: 'Mehmet S.',
    customerTitle: 'Ankara',
    rating: 5,
    comment: 'Müşteri hizmetleri çok ilgili, iade süreci sorunsuz işledi.',
    avatarUrl: null,
    approvedAt: '2026-02-01T14:00:00.000Z',
  },
  {
    id: 't-003',
    customerName: 'Zeynep D.',
    customerTitle: 'İzmir',
    rating: 4,
    comment: 'Beden tablosu doğruydu, ürün tam oturdu. Fiyat-performans iyi.',
    avatarUrl: null,
    approvedAt: '2026-02-12T09:30:00.000Z',
  },
];

const blogPosts = [
  {
    id: 'bp-001',
    slug: 'yaz-modasi-2026',
    title: '2026 Yaz Modası Trendleri',
    excerpt: 'Bu sezon öne çıkan renkler, kesimler ve kombin önerileri.',
    imageUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=800',
    publishedAt: '2026-03-01T10:00:00.000Z',
    readingTimeMin: 5,
  },
  {
    id: 'bp-002',
    slug: 'kapsul-dolap',
    title: 'Kapsül Dolap Nasıl Oluşturulur',
    excerpt: 'Az parçayla çok kombin: sürdürülebilir stil rehberi.',
    imageUrl: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800',
    publishedAt: '2026-03-10T12:00:00.000Z',
    readingTimeMin: 7,
  },
  {
    id: 'bp-003',
    slug: 'aksesuar-secimi',
    title: 'Aksesuar Seçiminin Gücü',
    excerpt: 'Doğru aksesuarla sade bir kombini nasıl dönüştürürsünüz?',
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=800',
    publishedAt: '2026-03-18T15:00:00.000Z',
    readingTimeMin: 4,
  },
];

export const demoData: InMemoryStorefrontData = {
  products,
  categories,
  brands,
  banners,
  testimonials,
  blogPosts,
};